name: gift_of_the_nile
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
  circle_list: ^1.0.5
  auto_size_text: ^3.0.0
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  timeline_list: ^0.0.6
  flutter_rating_bar: ^4.0.1
  dio: ^5.2.1+1
  marquee: ^2.2.3
  flutter_html: ^2.2.1
  path_provider: ^2.0.15
  path:
#  flutter_full_pdf_viewer: ^1.0.6
#  esys_flutter_share: ^1.0.2
  youtube_player_flutter: ^8.1.2
  android_intent: ^2.0.2
  intro_slider: ^4.2.0
  flutter_share: ^2.0.0
  geocoding: ^2.1.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_hooks: ^0.18.6
  sliver_snap: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.0
  lint: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/data/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf

    - family: Egyptian
      fonts:
        - asset: assets/fonts/AncientEgyptianHieroglyphs.otf

